model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: ???
  mode: ???
  save_top_k: ???
  save_last: false
  save_weights_only: false
  verbose: true
  dirpath: ${ckpt_dir} 
  filename: '{epoch}'